In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.1'

# Practice

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
b = np.array((6,7,8))

In [7]:
b

array([6, 7, 8])

In [8]:
type(a)

numpy.ndarray

In [9]:
type(b)

numpy.ndarray

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [12]:
np.arange(1.0, 3.0, 0.5, dtype='float64')

array([1. , 1.5, 2. , 2.5])

In [13]:
np.arange(0.13, 0.16, step=0.01)

array([0.13, 0.14, 0.15])

In [14]:
np.arange(0.12, 0.16, step=0.01)

array([0.12, 0.13, 0.14, 0.15, 0.16])

In [18]:
np.linspace(0.12, 0.16, num=5, endpoint=True, retstep=False, dtype=None, axis=0)

array([0.12, 0.13, 0.14, 0.15, 0.16])

In [20]:
a = np.array([[1,2,3], [4,5,6]])

In [21]:
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
a.shape

(2, 3)

In [23]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.empty((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.random.rand(2,3) #[0,1) uniform

array([[0.97165272, 0.77969267, 0.11466028],
       [0.83680674, 0.39843207, 0.16760128]])

In [27]:
np.random.randn(2,3) # (-1, 1)

array([[-0.64262819,  0.09849005,  0.04554339],
       [-1.19014196,  1.87980035,  1.2905268 ]])

In [52]:
np.random.randint(0, 100, 5)

array([27, 30, 26, 75, 77])

In [47]:
np.random.random_sample(10)

array([0.73090207, 0.12666521, 0.69212699, 0.4220664 , 0.45333336,
       0.15616583, 0.96276463, 0.05740275, 0.89508261, 0.40312149])

In [48]:
np.random.random(10)

array([0.82825582, 0.43151985, 0.85650856, 0.0031594 , 0.35785905,
       0.90932509, 0.17693514, 0.02744967, 0.41653974, 0.23298061])

In [51]:
np.random.sample(10)

array([0.83467775, 0.38948884, 0.33741079, 0.09286453, 0.30721568,
       0.05032149, 0.04075076, 0.82727782, 0.10078466, 0.68263037])

In [54]:
a=np.arange(20)

In [56]:
a[3]

3

In [57]:
a[5:10]

array([5, 6, 7, 8, 9])

In [58]:
a[5:10:2]

array([5, 7, 9])

In [59]:
a[-1]

19

In [60]:
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [63]:
b=np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
b[:, 1:]

array([[2, 3],
       [5, 6]])

In [64]:
b.ndim

2

In [65]:
b.dtype

dtype('int32')

In [66]:
b.size

6

In [67]:
b.flat

In [70]:
b.data

In [71]:
b.itemsize

4

## Homework

#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [73]:
a = np.arange(0, 21, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

#2.呈上題，將以上數列取出偶數。

In [76]:
a[0:21:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#3.呈1題，將數列取出3的倍數。

In [77]:
a[0:21:3]

array([ 0,  3,  6,  9, 12, 15, 18])