In [1]:
import numpy as np 

## Practice

In [2]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]]) 

In [6]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
b[3]=100

In [10]:
a

array([[  0,   1,   2, 100],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [11]:
a.ravel(order='C') # by row

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [13]:
a.ravel(order='F') # by column

array([  0,   4,   8,   1,   5,   9,   2,   6,  10, 100,   7,  11])

In [27]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
a.size

15

In [20]:
a.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
a.sum(axis=1)

array([1, 5, 9])

In [24]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
b = np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
np.concatenate((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [31]:
c = np.arange(10).reshape((5,2))
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
np.stack((a,c), axis=0) # dimension will plus one

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]])

In [38]:
np.stack((a,c), axis=1)

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]],

       [[8, 9],
        [8, 9]]])

In [39]:
np.hstack((a,c))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [40]:
np.vstack((a,c))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [42]:
for row in a:
    print(row)

[0 1]
[2 3]
[4 5]
[6 7]
[8 9]


In [47]:
np.amax(a, axis=0)

array([8, 9])

In [48]:
np.amax(a, axis=1)

array([1, 3, 5, 7, 9])

In [52]:
np.argmax(a, axis=0)

array([4, 4], dtype=int64)

In [54]:
np.where(a>5, "Y", "N")

array([['N', 'N'],
       ['N', 'N'],
       ['N', 'N'],
       ['Y', 'Y'],
       ['Y', 'Y']], dtype='<U1')

In [9]:
## sort

In [3]:
b = np.random.randint(0, 20, size = (5,4))
b

array([[14,  5, 17, 14],
       [ 7,  9, 15,  9],
       [11, 15, 18,  0],
       [ 1, 14,  4, 14],
       [ 0, 19,  4,  9]])

In [6]:
np.sort(b) # default axis is 1

array([[ 5, 14, 14, 17],
       [ 7,  9,  9, 15],
       [ 0, 11, 15, 18],
       [ 1,  4, 14, 14],
       [ 0,  4,  9, 19]])

In [5]:
np.sort(b, axis=0)

array([[ 0,  5,  4,  0],
       [ 1,  9,  4,  9],
       [ 7, 14, 15,  9],
       [11, 15, 17, 14],
       [14, 19, 18, 14]])

In [8]:
np.argsort(b) # 傳回第幾名

array([[1, 0, 3, 2],
       [0, 1, 3, 2],
       [3, 0, 1, 2],
       [0, 2, 1, 3],
       [0, 2, 3, 1]], dtype=int64)

In [16]:
np.where(b>10)

(array([0, 0, 0, 1, 2, 2, 2, 3, 3, 4], dtype=int64),
 array([0, 2, 3, 2, 0, 1, 2, 1, 3, 1], dtype=int64))

## Homework

In [17]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))

In [31]:
array2 = array1.reshape((5,6), order='F') # by row is order='C'
array2

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [3]:
#2.呈上題的array，找出被6除餘1的數的索引

In [40]:
np.where(array2 % 6 == 1, "Y", "N")

array([['N', 'N', 'N', 'N', 'N', 'Y'],
       ['Y', 'N', 'N', 'N', 'N', 'N'],
       ['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'N', 'Y', 'N', 'N', 'N'],
       ['N', 'N', 'N', 'Y', 'N', 'N']], dtype='<U1')

In [41]:
np.where (array2 % 6 == 1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))