## Practice

In [29]:
import numpy as np

In [30]:
np.add(1.0, 3.0)

4.0

In [7]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 2, 2, 2, 2])

In [8]:
a+b

array([3, 4, 5, 6, 7])

In [9]:
np.add(a, b)

array([3, 4, 5, 6, 7])

In [15]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
a.sum()

45

In [17]:
np.sum(a)

45

In [18]:
np.sum(a, axis=0)

array([ 5,  7,  9, 11, 13])

In [2]:
import numpy as np 

In [19]:
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#請寫下程式
V1 = 20000
V0 = 20

In [31]:
db = 20 * np.log10(V1/V0)
print(db, '分貝')

60.0 分貝


In [4]:
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = ?
#請寫下程式

In [32]:
V1_30 = np.power(10, 30/20 * np.log10(30))
V1_50 = np.power(10, 50/20 * np.log10(50))

In [33]:
print(V1_30/V1_50, "倍")

0.009295160030897798 倍
