In [2]:
import numpy as np

## Practice

In [5]:
np.isnan(np.array([1.0, np.nan, 3.0]))

array([False,  True, False])

In [6]:
np.isfinite(1.0)

True

In [7]:
np.isfinite(np.nan)

False

In [8]:
np.isinf([np.inf, -np.inf, 1.0, np.nan, np.PINF])

array([ True,  True, False, False,  True])

In [9]:
np.isposinf(np.PINF)

True

In [10]:
np.isneginf(np.NIbNF), np.isneginf(np.nan)

(True, False)

In [11]:
np.isnat(np.array(["NaT", "2020-06-26"], dtype="datetime64[ns]"))

array([ True, False])

In [12]:
a = np.array([1, 2, 3])

In [13]:
np.isscalar(a[2])

True

In [14]:
np.isscalar(a)

False

In [15]:
np.isscalar(np.pi)

True

In [16]:
np.isscalar(np.array(3.0))

False

In [17]:
# 包含實數與複數的陣列
b = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

In [18]:
np.isreal(b)

array([False,  True,  True,  True,  True, False])

In [19]:
np.iscomplex(b)

array([ True, False, False, False, False,  True])

In [20]:
np.iscomplexobj(b)

True

In [21]:
np.isrealobj(b)

False

In [22]:
# 陣列中全部是實數
np.isrealobj(np.array([1, 2.0, 3.1]))

True

In [23]:
np.array_equal(np.array([1, 2, 3]), np.array([1, 2, 3]))

True

In [24]:
np.array_equal(np.array([1, 2, 3]), np.array([1, 2, 5]))

False

In [25]:
np.array_equiv(np.array([1, 2, 3]), np.array([1, 2, 3]))

True

In [26]:
np.array_equiv(np.array([1, 2, 3]), np.array([[1, 2, 3], [1, 2, 3]]))

True

In [27]:
np.array_equiv(np.array([1, 1, 1]), np.array([1]))

True

In [28]:
# 形狀與元素值均相同
np.equal(np.array([1, 2, 3]), np.array([1, 2, 3]))

array([ True,  True,  True])

In [29]:
# 符合廣播規則的相等
np.equal(np.array([1, 1, 1]), np.ones(1))

array([ True,  True,  True])

In [30]:
# 不等於的比較，符合廣播規則
np.not_equal([1, 2], [[1, 3],[1, 4]])

array([[False,  True],
       [False,  True]])

In [31]:
x = np.array([True, True, False, False])
y = np.array([True, False, True, False])

In [32]:
np.logical_and(x, y)

array([ True, False, False, False])

In [33]:
np.logical_or(x, y)

array([ True,  True,  True, False])

In [34]:
np.logical_not(x)

array([False, False,  True,  True])

In [35]:
np.logical_xor(x, y)

array([False,  True,  True, False])

In [36]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
np.logical_and(a > 1, a < 4)

array([False, False,  True,  True, False])

In [38]:
np.all([-1, np.nan, 5])

True

In [40]:
np.all([-1, 4, 0]) # 有零

False

In [41]:
np.any([[True, False], [True, True]])

True

In [42]:
np.any([[True, False], [False, False]], axis=0)

array([ True, False])

## HW

In [3]:
#1.有多少學生英文成績比數學成績高?

In [43]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [44]:
np.greater(english_score, math_score)

array([False,  True,  True, False, False,  True])

In [49]:
np.unique(np.greater(english_score, math_score), return_counts=True)

(array([False,  True]), array([3, 3], dtype=int64))

In [4]:
#2.是否全班同學最高分都是國文?

In [59]:
np.greater_equal(chinese_score, english_score)

array([ True,  True,  True,  True,  True,  True])

In [61]:
np.greater_equal(chinese_score, math_score)

array([ True,  True,  True,  True,  True,  True])

In [57]:
np.logical_and(np.greater_equal(chinese_score, english_score), np.greater_equal(chinese_score, math_score))

array([ True,  True,  True,  True,  True,  True])