## Practice

In [2]:
import numpy as np

In [4]:
with open('data/one_array.npy', 'wb') as f:
    np.save(f, np.array([1, 2]))

In [5]:
np.load('data/one_array.npy')

array([1, 2])

In [6]:
with open('data/test.npy', 'wb') as f:
    np.save(f, np.array([1, 2]))
    np.save(f, np.array([1, 3]))
    np.save(f, np.array([1, 4]))
    np.save(f, np.array([1, 3]))

In [8]:
with open('data/test.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
    c = np.load(f)
    d = np.load(f)

print(a, b, c, d)

[1 2] [1 3] [1 4] [1 3]


In [9]:
x = np.arange(10)
y = np.array([1, 2, 3])
z = np.random.rand(10)

with open('data/multi_array.npz', 'wb') as f:
    np.savez(f, array1=x, array2=y, array3=z)

In [11]:
npzfile = np.load('data/multi_array.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [12]:
npzfile.files

['array1', 'array2', 'array3']

In [13]:
print(npzfile['array1'])
print(npzfile['array2'])
print(npzfile['array3'])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.40322843 0.02185221 0.14451943 0.35145567 0.99265446 0.06271776
 0.94902681 0.55665965 0.66941177 0.51372589]


In [3]:
x = y = z = np.arange(0.0,5.0,1.0)
x

array([0., 1., 2., 3., 4.])

In [5]:
y = np.arange(10).reshape(2, 5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
np.savetxt('data/test.out', [x], delimiter=',')

In [7]:
# %load data/test.out
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00


In [8]:
np.savetxt('data/test.gz', [x], delimiter=',')

In [9]:
np.savetxt('data/test.csv', y, delimiter=',')

In [10]:
# %load data/test.csv
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00


In [12]:
np.savetxt('data/test.out', x, fmt='%1.4e', delimiter=',', header='this is,\nheader', footer='this is footer')

In [13]:
# %load data/test.out
# this is,
# header
0.0000e+00
1.0000e+00
2.0000e+00
3.0000e+00
4.0000e+00
# this is footer


In [14]:
np.loadtxt('data/test.out', delimiter=',', dtype='f4')

array([0., 1., 2., 3., 4.], dtype=float32)

In [15]:
np.genfromtxt("data/test.csv", delimiter=",")

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [16]:
np.genfromtxt("data/test.gz", delimiter=",")

array([0., 1., 2., 3., 4.])

## HW

In [17]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [28]:
with open('data/hw_multi_array.npz', 'wb') as f:
    np.savez(f, array1=array1, array2=array2)

In [1]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [29]:
npzfile = np.load('data/hw_multi_array.npz')
type(npzfile)
npzfile.files

['array1', 'array2']

In [23]:
array3 = np.array([7,8,9])

In [26]:
with open('data/hw_multi_array_new.npz', 'wb') as f:
    np.savez(f, array1=array1, array2=array2, array3=array3)

In [27]:
npzfile = np.load('data/hw_multi_array_new.npz')
type(npzfile)
npzfile.files

['array1', 'array2', 'array3']