## Practice

In [5]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

In [6]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
np.dot(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [9]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(5))

In [10]:
a

array([5, 6, 8, 6, 1])

In [11]:
b

array([6, 4, 8, 1, 8])

In [12]:
np.inner(a, b)

132

In [13]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(6))

In [14]:
a

array([5, 6, 8, 6, 1])

In [15]:
b

array([6, 4, 8, 1, 8, 5])

In [16]:
np.outer(a, b)

array([[30, 20, 40,  5, 40, 25],
       [36, 24, 48,  6, 48, 30],
       [48, 32, 64,  8, 64, 40],
       [36, 24, 48,  6, 48, 30],
       [ 6,  4,  8,  1,  8,  5]])

In [17]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

np.matmul(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [18]:
A @ B

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [19]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
A

array([[ 3,  0, -1],
       [ 2,  4,  1],
       [ 7,  2,  3]])

In [20]:
np.trace(A) # 對角線相加

10

## HW

作業目標
活用矩陣運算，實做線性代數
作業重點
線性代數公式應用
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:
array1 = np.array([[10, 8], [3, 5]])

運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
運用上列array計算特徵值、特徵向量?
運用上列array計算SVD?

In [1]:
import numpy as np

In [21]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

In [22]:
rev = np.linalg.inv(array1)

In [23]:
array1 @ rev

array([[1., 0.],
       [0., 1.]])

In [3]:
#2. 運用上列array計算特徵值、特徵向量?

In [24]:
w, v = np.linalg.eig(array1)

In [25]:
w

array([13.,  2.])

In [26]:
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [27]:
np.linalg.eigvals(array1)

array([13.,  2.])

In [4]:
#3. 運用上列array計算SVD?

In [28]:
u, s, vh = np.linalg.svd(array1)

In [29]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [30]:
s

array([13.94721714,  1.86417116])

In [31]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])